import { SKILLS } from '../../constants/skills';
import { STACK } from '../../constants/stack';

const { OTHER_SKILLS, FRONTEND, BACKEND } = SKILLS;

const stack_enUS = {
  title: 'Stack',
  return: 'return [',
  closeArray: ']',
  closeObj: '}',
  [OTHER_SKILLS]: {
    title: 'knowledges( developer ) {',
    [STACK[OTHER_SKILLS].ARCHITECTURE]: 'Architecture',
    [STACK[OTHER_SKILLS].MICROSERVICES]: 'Microservices',
    [STACK[OTHER_SKILLS].RN]: 'React native',
    [STACK[OTHER_SKILLS].KOTLIN]: 'Kotlin',
    [STACK[OTHER_SKILLS].AWS]: 'AWS Amazon Web Services',
    [STACK[OTHER_SKILLS].GCP]: 'GCP - Google Cloud Platform',
    [STACK[OTHER_SKILLS].FIREBASE]: 'Firebase',
    [STACK[OTHER_SKILLS].REDSHIFT]: 'AWS Redshift',
    [STACK[OTHER_SKILLS].AIRFLOW]: 'Airflow',
    [STACK[OTHER_SKILLS].DOCKER]: 'Docker',
    [STACK[OTHER_SKILLS].KUBERNETES]: 'Kubernetes',
    [STACK[OTHER_SKILLS].NGINX]: 'NGINX Server',
    [STACK[OTHER_SKILLS].GIT]: 'git',
    [STACK[OTHER_SKILLS].GIT_FLOW]: 'Git Flow',
    [STACK[OTHER_SKILLS].CI_CD]: 'CI/CD',
    [STACK[OTHER_SKILLS].CIRCLE_CI]: 'Circle CI',
    [STACK[OTHER_SKILLS].VIM]: 'Vim',
    [STACK[OTHER_SKILLS].JWT]: 'JWT',
  },
  [BACKEND]: {
    title: 'knowledges( backend ) {',
    [STACK[BACKEND].SERVERLESS]: 'Serverless',
    [STACK[BACKEND].NODE_JS]: 'NodeJS',
    [STACK[BACKEND].PYTHON]: 'Python',
    [STACK[BACKEND].ELIXIR]: 'Elixir',
    [STACK[BACKEND].FLASK]: 'Flask',
    [STACK[BACKEND].JAVA]: 'Java',
    [STACK[BACKEND].SPRING_BOOT]: 'Spring Boot',
    [STACK[BACKEND].SPRING_DATA]: 'Spring Data',
    [STACK[BACKEND].POSTGRES]: 'PostgreSQL',
    [STACK[BACKEND].MONGO_DB]: 'MongoDB',
    [STACK[BACKEND].RABBIT_MQ]: 'RabbitMQ',
    [STACK[BACKEND].KAFKA]: 'Kafka',
    [STACK[BACKEND].REDIS]: 'Redis',
    [STACK[BACKEND].GRAPHQL]: 'GraphQL',
    [STACK[BACKEND].REST_API]: 'Rest Apis',
    [STACK[BACKEND].OOP]: 'OOP',
    [STACK[BACKEND].MVC]: 'MVC (Model View Controller)',
    [STACK[BACKEND].ORM]: 'ORM (Object Relational Mapper)',
    [STACK[BACKEND].FUNCTIONAL_PROGRAMING]: 'Functional programming',
    [STACK[BACKEND].APOLLO_SERVER]: 'Apollo Server',
  },
  [FRONTEND]: {
    title: 'knowledges( frontend ) {',
    [STACK[FRONTEND].ES2015]: 'ES2015++',
    [STACK[FRONTEND].HTML]: 'html5',
    [STACK[FRONTEND].CSS]: 'css3',
    [STACK[FRONTEND].CSS_MODULES]: 'CSS Modules',
    [STACK[FRONTEND].TYPE_SCRIPT]: 'Typescript',
    [STACK[FRONTEND].ESLINT]: 'ESLint',
    [STACK[FRONTEND].REACT]: 'ReactJs',
    [STACK[FRONTEND].ANGULAR]: 'Angular',
    [STACK[FRONTEND].ANGULARJS]: 'AngularJS',
    [STACK[FRONTEND].REDUX]: 'Redux',
    [STACK[FRONTEND].WEBPACK]: 'Webpack',
    [STACK[FRONTEND].JEST]: 'Jest',
    [STACK[FRONTEND].REACT_TESTING_LIBRARY]: 'React testing library',
    [STACK[FRONTEND].NPM]: 'npm',
    [STACK[FRONTEND].YARN]: 'Yarn',
    [STACK[FRONTEND].APOLLO]: 'Apollo Client',
    [STACK[FRONTEND].MATERIAL_DESIGN]: 'Material Design',
  },
};

export { stack_enUS };
